# Generated by Django 3.1.7 on 2021-03-21 21:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_auth', models.CharField(max_length=32)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
