# Generated by Django 3.1.7 on 2021-03-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='id_pizza',
            field=models.CharField(default=123123123, max_length=32),
            preserve_default=False,
        ),
    ]
